version: '3.12'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  webapp:
    build:
      context: .  # Путь к папке с Dockerfile_webapp для FastAPI
      dockerfile: Dockerfile_webapp
    container_name: webapp
    volumes:
      - ./cache:/webapp/cache
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  bot:
    build:
      context: .  # Путь к папке с Dockerfile_webapp для бота
      dockerfile: Dockerfile_bot
    container_name: bot
    volumes:
      - ./cache:/bot/cache
    depends_on:
      - redis
      - webapp  # Если боту нужно обращаться к API
    environment:
      - REDIS_HOST=redis
